version: '2'

services:
  nginx:
    image: nginx
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./fastcgi_params:/etc/nginx/fastcgi_params
       - ./my-next-app/out:/tmp/my-next-app

    ports:
      - "8080:8080"
    restart: always

  php:
    image: php:7.4-fpm
    restart: always
    volumes:
        - "./my-php-app:/var/www/html"